Repository pickple-ecommerce/backend, pull requests merged in 2024-10, with the labels that each got.

#17 feat: Delivery 서비스에 Kafka 연동 및 배송 생성 구현
  common-module/src/main/java/com/pickple/common_module/infrastructure/messaging/EventSerializer.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryCreateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryCreateResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryMessageProducerService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryStatus.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryType.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/service/DeliveryDomainService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/messaging/DeliveryMessageConsumerService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/messaging/events/DeliveryCreateRequestEvent.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryRepository.java
  delivery-service/src/main/resources/application-dev.yml
  delivery-service/src/test/java/com/pickple/delivery/DeliveryCassandraRepositoryTest.java
  docker-compose.yml
Labels: feat

#18 feat : Payment 서비스에 Kafka 연동 및 결제 생성 구현
  payment-service/src/main/java/com/pickple/payment_service/application/dto/PaymentRespDto.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentEventService.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/pickple/payment_service/domain/model/Payment.java
  payment-service/src/main/java/com/pickple/payment_service/domain/model/PaymentStatusEnum.java
  payment-service/src/main/java/com/pickple/payment_service/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/PaymentEventConsumer.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/OrderCreatedEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentSuccessEvent.java
  payment-service/src/main/java/com/pickple/payment_service/presentation/controller/PaymentController.java
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application.yml
Labels: feat

#20 fix : EventSerializer 삭제 및 common module에서 import + gradle 파일 추가
  payment-service/.gitignore
  payment-service/build.gradle
  payment-service/gradle/wrapper/gradle-wrapper.jar
  payment-service/gradle/wrapper/gradle-wrapper.properties
  payment-service/gradlew
  payment-service/gradlew.bat
  payment-service/settings.gradle
  payment-service/src/main/java/com/pickple/payment_service/PaymentServiceApplication.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentEventService.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentSuccessEvent.java
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/test/java/com/pickple/payment_service/PaymentServiceApplicationTests.java
Labels: fix

#27 Order 엔티티 수정, docker-compose 수정
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Order.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/OrderDetail.java
  docker-compose.yml
Labels: fix

#28 feat: #23 멀티 모듈 구성, #29 Github Actions workflow 추가
  .github/workflows/gradle.yml
  build.gradle
  commerce-service/settings.gradle
  common-module/README.md
  common-module/build.gradle
  common-module/settings.gradle
  common-module/src/main/java/com/pickple/common_module/CommonModuleApplication.java
  delivery-service/settings.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  payment-service/settings.gradle
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/PaymentEventConsumer.java
  settings.gradle
  user-service/settings.gradle
Labels: feat

#33 refactor: CommonResponse 이름 변경
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/VendorController.java
  common-module/src/main/java/com/pickple/common_module/presentation/dto/ApiResponse.java
  payment-service/src/main/java/com/pickple/payment_service/presentation/controller/PaymentController.java
Labels: refactor

#40 feat: 배송 시작 API 구현 및 배송 생성 시 이벤트 발행
  .gitignore
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryStartRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryStartResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/DeliveryCreateFailureEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/DeliveryCreateResponseEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryMessageProducerService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryCarrier.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryStatus.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryType.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/exception/DeliveryErrorCode.java
  delivery-service/src/main/java/com/pickple/delivery/exception/DeliveryExceptionHandler.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/SecurityConfig.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/messaging/DeliveryMessageConsumerService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/security/CustomAuthenticationFilter.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/request/DeliveryStartRequest.java
  delivery-service/src/main/resources/application-dev.yml
Labels: feat

#42 feat: DeliveryDetail 생성 요청 API 구현
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryDetailCreateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryDetailCreateResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/DeliveryCreateResponseEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryDetailMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/DeliveryDetail.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryDetailRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/service/DeliveryDomainService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/AuditorAwareImpl.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryDetailCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryDetailRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/request/DeliveryDetailCreateRequest.java
  delivery-service/src/test/java/com/pickple/delivery/DeliveryCassandraRepositoryTest.java
Labels: feat

#44 feat : Notification Kassandra 연동
  db-init/notification/init-notification.cql
  docker-compose.yml
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application.yml
  payment-service/build.gradle
Labels: fix, feat, init

#46 feat: 사용자 배송 조회 API 구현
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryDetailInfoDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryInfoDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryCreateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryDetailCreateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryStartRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryDetailCreateResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryInfoResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryStartResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryDetailMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/DeliveryDetail.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryDetailRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/projection/DeliveryDetailInfoProjection.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/projection/DeliveryInfoProjection.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryDetailCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/resources/application-dev.yml
Labels: feat

#45 Feature/commerce
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/CommerceServiceApplication.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/VendorService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Vendor.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/VendorRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/VendorRepositoryCustom.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/VendorRepositoryCustomImpl.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/QuerydslConfig.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/VendorController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/VendorUpdateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/VendorResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/VendorUpdateResponseDto.java
  common-module/build.gradle
  docker-compose.yml
Labels: feat

#51 feat: Payment에 Kafka 메세징 처리 구현
  payment-service/src/main/java/com/pickple/payment_service/application/dto/PaymentRespDto.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentEventService.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/pickple/payment_service/domain/model/Payment.java
  payment-service/src/main/java/com/pickple/payment_service/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/pickple/payment_service/exception/PaymentErrorCode.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/PaymentEventConsumer.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCancelFailureEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCancelRequestEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCancelResponseEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCreateFailureEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCreateRequestEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCreateResponseEvent.java
Labels: enhancement, refactor

#53 feat: Payment Controller 구현 및 AuditAware 추가
  payment-service/build.gradle
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/pickple/payment_service/domain/model/Payment.java
  payment-service/src/main/java/com/pickple/payment_service/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/configuration/AuditAwareImpl.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/configuration/JpaConfig.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCreateResponseEvent.java
  payment-service/src/main/java/com/pickple/payment_service/presentation/controller/PaymentController.java
Labels: enhancement, feat

#55 상품, 예약 상품, 재고 Entity 구현
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/PreOrderDetails.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Product.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Stock.java
  user-service/src/main/java/com/pickple/user/domain/repository/UserRepositoryImpl.java
Labels: feat

#58 feat: Apache Cassandra에서 Mongo DB로 마이그레이션
  db-init/delivery/init-delivery.cql
  delivery-service/build.gradle
  delivery-service/src/main/java/com/pickple/delivery/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryDetailInfoDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryDetailCreateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryDetailCreateResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryDetailMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/BaseEntity.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/DeliveryDetail.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/DeliveryDetailId.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/deleted/DeliveryDeleted.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/deleted/DeliveryDetailDeleted.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryDetailRepository.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/deleted/DeliveryDetailDeletedRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/AuditorConfig.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryDetailCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryMongoRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/deleted/DeliveryDeletedMongoRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/deleted/DeliveryDetailDeletedCassandraRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/request/DeliveryDetailCreateRequest.java
  delivery-service/src/main/resources/application-dev.yml
  delivery-service/src/test/java/com/pickple/delivery/DeliveryMongoRepositoryTest.java
  docker-compose.yml
Labels: feat

#60 docs: Grafana & Prometheus 연동을 위한 설정 파일 추가 및 수정
  .github/prometheus/config/prometheus.yml
  auth-service/build.gradle
  auth-service/src/main/resources/application-dev.yml
  commerce-service/build.gradle
  commerce-service/src/main/resources/application-dev.yml
  delivery-service/build.gradle
  delivery-service/src/main/resources/application-dev.yml
  docker-compose.yml
  eureka-server/build.gradle
  eureka-server/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-dev.yml
  user-service/build.gradle
  user-service/src/main/resources/application-dev.yml
Labels: docs, init

#62 feat: 배송 수정, 검색, 전체 조회 API 구현
  delivery-service/src/main/java/com/pickple/delivery/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryStartRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/request/DeliveryUpdateRequestDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryCarrier.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/enums/DeliveryStatus.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/exception/DeliveryErrorCode.java
  delivery-service/src/main/java/com/pickple/delivery/exception/DeliveryExceptionHandler.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryMongoRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/request/DeliveryUpdateRequest.java
Labels: feat

#64 상품 생성 api 구현
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/ProductResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/StockResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/ProductService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/StockService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Product.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Stock.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/StockRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceExceptionHandler.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/SecurityConfig.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/security/CustomPreAuthFilter.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/ProductController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/ProductCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/StockCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/VendorResponseDto.java
Labels: fix, feat

#65 feat: 배송 상태 조회 API 구현
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryStatusResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/SecurityConfig.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/security/CustomAuthenticationFilter.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
Labels: feat

#68 feat: #50 상품 RUD, 재고 조회, 수정 API 및 감소 메서드 구현
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/StockByProductDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/ProductService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/StockService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Product.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Stock.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/StockRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/ProductController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/StockController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/ProductUpdateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/StockUpdateRequestDto.java
  commerce-service/src/test/java/com/pickple/commerceservice/application/service/StockServiceTest.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  gateway/src/main/resources/application.yml
Labels: feat, test

#67 [fix: #60, #53] Payment 오류 해결 및 docker-compose 재설정
  .gitignore
  docker-compose.yml
  github/grafana-data/grafana.db
  grafana/provisioning/dashboards/gf_dashboard.json
  grafana/provisioning/datasources/gf_datasource.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/pickple/payment_service/exception/PaymentExceptionHandler.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/configuration/JpaConfig.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/configuration/SecurityConfig.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/security/CustomPreAuthFilter.java
  payment-service/src/main/resources/application-dev.yml
  prometheus/config/prometheus.yml
Labels: fix, enhancement

#70 feat #69 예약구매 상품 관련 기능 구현
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/PreOrderResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/PreOrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/PreOrderDetails.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/PreOrderRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/PreOrderController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/PreOrderCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/PreOrderUpdateRequestDto.java
  gateway/src/main/resources/application.yml
Labels: feat

#72 Feature/order
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/TemporaryStorageService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/VendorService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Order.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/OrderDetail.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/OrderStatus.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Vendor.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/OrderRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/AuditAwareImpl.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/OrderMessagingProducerService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/events/DeliveryCreateRequestEvent.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/events/PaymentCreateRequestEvent.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/OrderController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/VendorController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/OrderCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/VendorCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/OrderCreateResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/VendorCreateResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/response/VendorResponseDto.java
  commerce-service/src/main/resources/application-dev.yml
Labels: feat

#73 feat: #47 Kafka Listener 생성
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/OrderMessagingConsumerService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/OrderMessagingProducerService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/events/PaymentCreateRequestEvent.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/events/PaymentCreateResponseEvent.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/PaymentEventConsumer.java
  payment-service/src/main/java/com/pickple/payment_service/infrastructure/messaging/events/PaymentCreateRequestEvent.java
  payment-service/src/main/resources/application-dev.yml
Labels: feat

#71 refactor: 그라파나 Provisioning 설정 리팩토링
  .github/8.10.2/checksums/checksums.lock
  .github/8.10.2/dependencies-accessors/gc.properties
  .github/8.10.2/fileChanges/last-build.bin
  .github/8.10.2/fileHashes/fileHashes.lock
  .github/8.10.2/gc.properties
  .github/buildOutputCleanup/buildOutputCleanup.lock
  .github/buildOutputCleanup/cache.properties
  .github/vcs-1/gc.properties
  .gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/-1811975282/backend.gateway.main.iml
  .idea/modules/252020312/backend.common-module.main.iml
  .idea/modules/backend.payment-service.main.iml
  .idea/modules/notification-service.main.iml
  .idea/sqldialects.xml
  .idea/vcs.xml
  docker-compose.yml
  notification-service/.gitignore
  notification-service/build.gradle
  notification-service/gradle/wrapper/gradle-wrapper.jar
  notification-service/gradle/wrapper/gradle-wrapper.properties
  notification-service/gradlew
  notification-service/gradlew.bat
  notification-service/settings.gradle
  notification-service/src/main/java/com/pickple/notification_service/NotificationServiceApplication.java
  notification-service/src/main/java/com/pickple/notification_service/domain/Notification.java
  notification-service/src/test/java/com/pickple/notification_service/NotificationServiceApplicationTests.java
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/pickple/payment_service/presentation/controller/PaymentController.java
  settings/grafana/provisioning/alerting/gf_alertrule.yml
  settings/grafana/provisioning/alerting/gf_contactpoint.yml
  settings/grafana/provisioning/alerting/gf_notification_policy.yml
  settings/grafana/provisioning/dashboards/gf_dashboards.yml
  settings/grafana/provisioning/dashboards/server-check.json
  settings/grafana/provisioning/datasources/gf_datasource.yml
  settings/prometheus/config/prometheus.yml
Labels: fix, refactor

#76 Delete .idea directory
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/-1811975282/backend.gateway.main.iml
  .idea/modules/252020312/backend.common-module.main.iml
  .idea/modules/backend.payment-service.main.iml
  .idea/modules/notification-service.main.iml
  .idea/sqldialects.xml
  .idea/vcs.xml
Labels: refactor

#78 Feature/order
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/TemporaryStorageService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/RedisConfig.java
Labels: refactor

#80 refactor: #79 지연로딩으로 변경
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/OrderDetail.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/PreOrderDetails.java
Labels: refactor

#83 feat: 배송 서비스 성능 개선
  delivery-service/build.gradle
  delivery-service/src/main/java/com/pickple/delivery/application/dto/DeliveryDetailInfoDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryInfoResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/RedisConfig.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryMongoRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/resources/application-dev.yml
Labels: feat

#86 fix: Notification service 실행 오류 해결 - 엔티티 참조 변수명 수정
  notification-service/src/main/java/com/pickple/notification_service/domain/model/Channel.java
Labels: fix

#89 fix: docker compose dev 내부 잘못된 경로 수정
  docker/docker-compose.dev.yml
Labels: fix

#87 feat: Github Actions CI 구성
  .github/workflows/build-ci.yml
  .github/workflows/docker-integrate-ci.yml
  .github/workflows/gradle.yml
  .github/workflows/integrate-ci.yml
  db-init/user/init-user.sql
  docker/docker-compose.dev.yml
Labels: feat

#93 feat: #92 주문 ID로 배송 조회 API 구현
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/repository/DeliveryMongoRepository.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
Labels: feat

#95 Feature/product search
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/ProductSearchResDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/ProductService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepositoryCustom.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/ProductRepositoryImpl.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/QuerydslConfig.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/ProductController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/ProductSearchReqDto.java
Labels: feat

#97 예약구매 주문 생성 api 구현
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/OrderController.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/PreOrderRequestDto.java
  commerce-service/src/test/java/com/pickple/commerceservice/application/service/OrderServiceTest.java
Labels: feat

#98 Feature/order
  commerce-service/src/main/java/com/pickple/commerceservice/application/dto/OrderByVendorResponseDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/OrderRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/DeliveryClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/OrderController.java
Labels: feat

#99 chore: 관리자용 슬랙 url 요청 API 구현 및 수신 이메일 받는 User feign 추가
  .gitignore
  eureka-server/build.gradle
  notification-service/build.gradle
  notification-service/src/main/java/com/pickple/notification_service/NotificationServiceApplication.java
  notification-service/src/main/java/com/pickple/notification_service/application/service/EmailService.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/feign/UserFeignClient.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/messaging/events/EmailCreateRequestEvent.java
  notification-service/src/main/java/com/pickple/notification_service/presentation/NotificationController.java
  payment-service/build.gradle
  settings/grafana/provisioning/alerting/gf_contactpoint.yml
Labels: enhancement, feat

#100 test 코드 삭제 및 설정 파일 코드 수정
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderEventService.java
  commerce-service/src/main/resources/application-dev.yml
  commerce-service/src/main/resources/application-prod.yml
Labels: feat

#101 refactor: 슬랙 url application-dev.yml에 추가하는거로 수정
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/DeliveryClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/PaymentClient.java
  commerce-service/src/main/resources/application-dev.yml
  commerce-service/src/main/resources/application-prod.yml
  notification-service/src/main/java/com/pickple/notification_service/presentation/NotificationController.java
  notification-service/src/main/resources/application-dev.yml
Labels: refactor

#104 fix: delivery detail 수정 시 명시적 save 추가
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryDetailApplicationService.java
Labels: bug, fix

#105 예약구매 생성 api 동시성 처리하여 구현
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/StockService.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/RedissonConfig.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/facade/RedissonLockStockFacade.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/PreOrderRequestDto.java
  commerce-service/src/test/java/com/pickple/commerceservice/application/service/OrderServiceTest.java
  commerce-service/src/test/java/com/pickple/commerceservice/application/service/StockServiceTest.java
  commerce-service/src/test/java/com/pickple/commerceservice/infrastructure/facade/RedissonLockStockFacadeTest.java
  user-service/src/main/java/com/pickple/user/application/service/UserService.java
  user-service/src/main/java/com/pickple/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/pickple/user/presentation/controller/UserController.java
Labels: feat

#108 feat: 배송 완료 API 구현
  delivery-service/src/main/java/com/pickple/delivery/application/events/DeliveryEndEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/pickple/delivery/exception/DeliveryErrorCode.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/resources/application-dev.yml
  delivery-service/src/main/resources/application-prod.yml
Labels: feat

#109 docs: 트래픽 알림 채널 추가 및 환경변수 편집
  .github/workflows/docker-integrate-ci.yml
  .github/workflows/integrate-ci.yml
  docker/docker-compose.infra.yml
  eureka-server/Dockerfile
  notification-service/src/main/java/com/pickple/notification_service/application/service/EmailService.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/feign/UserFeignClient.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/messaging/NotificationEventProducer.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/messaging/events/NotificationFailureResponse.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/messaging/events/NotificationSuccessResponse.java
  notification-service/src/main/resources/application-dev.yml
  payment-service/src/main/java/com/pickple/payment_service/application/service/PaymentService.java
  settings/grafana/provisioning/alerting/gf_alertrule.yml
  settings/grafana/provisioning/alerting/gf_contactpoint.yml
  settings/grafana/provisioning/alerting/gf_notification_policy.yml
  settings/grafana/provisioning/dashboards/gf_dashboards.yml
  settings/grafana/provisioning/dashboards/pickple-dashboard.json
Labels: docs

#114 feat: 배송 상태 변경 시 알림 메시지 발행 및 배송 삭제 이벤트 발행
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/OrderRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/DeliveryClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/PaymentClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/OrderController.java
  commerce-service/src/main/resources/application-dev.yml
  commerce-service/src/main/resources/application-prod.yml
  delivery-service/build.gradle
  delivery-service/src/main/java/com/pickple/delivery/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/DeliveryEndEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/NotificationSendEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/port/OrderClient.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/feign/OrderFeignClient.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/resources/application-dev.yml
  delivery-service/src/main/resources/application-prod.yml
Labels: feat

#113 Feature/ 각 서비스에 loki 추가
  auth-service/build.gradle
  auth-service/src/main/resources/logback.xml
  commerce-service/build.gradle
  commerce-service/src/main/resources/logback.xml
  delivery-service/build.gradle
  delivery-service/src/main/resources/logback.xml
  docker/docker-compose.dev.yml
  docker/docker-compose.infra.yml
  docker/docker-compose.service.yml
  notification-service/build.gradle
  notification-service/src/main/resources/logback.xml
  payment-service/build.gradle
  payment-service/src/main/resources/logback.xml
  settings/grafana/loki/loki-config.yml
  settings/grafana/provisioning/dashboards/pickple-dashboard.json
  settings/grafana/provisioning/datasources/gf_datasource.yml
  user-service/build.gradle
  user-service/src/main/resources/logback.xml
Labels: docs, feat

#116 hotfix: IDE 콘솔에도 로그가 뜨도록 변경
  auth-service/src/main/resources/logback.xml
  commerce-service/src/main/resources/logback.xml
  delivery-service/src/main/resources/logback.xml
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-prod.yml
  notification-service/src/main/resources/logback.xml
  payment-service/src/main/resources/logback.xml
  settings/grafana/provisioning/dashboards/pickple-dashboard.json
  user-service/src/main/resources/logback.xml
Labels: fix

#117 chore: notification application.yml 수정
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-prod.yml
Labels: refactor

#111 feat: AWS CI/CD 파이프라인 구성
  .github/workflows/commerce-payment-cd.yml
  .github/workflows/delivery-notification-cd.yml
  .github/workflows/docker-integrate-ci.yml
  .github/workflows/eureka-gateway-cd.yml
  .github/workflows/user-auth-cd.yml
  docker/db-init/commerce/init-commerce.sql
  docker/db-init/notification/init-notification.sql
  docker/db-init/payment/init-payment.sql
  docker/db-init/user/init-user.sql
  docker/docker-compose.commerce-payment.yml
  docker/docker-compose.db.yml
  docker/docker-compose.delivery-notification.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.eureka-gateway.yml
  docker/docker-compose.infra.yml
  docker/docker-compose.kafka.yml
  docker/docker-compose.monitor.yml
  docker/docker-compose.redis.yml
  docker/docker-compose.service.yml
  docker/docker-compose.user-auth.yml
Labels: feat

#119 낙관적 락 구현 및 전략 설정
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/CommerceServiceApplication.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/StockRetryService.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/model/Stock.java
  commerce-service/src/main/java/com/pickple/commerceservice/domain/repository/StockRepository.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/facade/RedissonLockStockFacade.java
  commerce-service/src/main/resources/application-dev.yml
  commerce-service/src/test/java/com/pickple/commerceservice/infrastructure/facade/RedissonLockStockFacadeTest.java
  docker/docker-compose.dev.yml
  gateway/build.gradle
  gateway/src/main/resources/application-dev.yml
Labels: enhancement, feat

#128 fix: #123 feign 클라이언트에 @Primary 추가
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/DeliveryClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/PaymentClient.java
Labels: fix

#129 Feature/redis master slave
  auth-service/src/main/java/com/pickple/auth/infrastructure/config/RedisConfig.java
  auth-service/src/main/java/com/pickple/auth/infrastructure/config/RedisSentinelProperties.java
  auth-service/src/main/resources/application-dev.yml
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/RedisConfig.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/RedisSentinelProperties.java
  commerce-service/src/main/resources/application-dev.yml
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/RedisConfig.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/config/RedisSentinelProperties.java
  delivery-service/src/main/resources/application-dev.yml
  docker/docker-compose.dev.yml
  gateway/src/main/java/com/pickple/gateway/infrastructure/config/RedisConfig.java
  gateway/src/main/java/com/pickple/gateway/infrastructure/config/RedisSentinelProperties.java
  gateway/src/main/resources/application-dev.yml
  user-service/build.gradle
  user-service/src/main/resources/application-dev.yml
Labels: fix, enhancement, feat

#131 fix: CI/CD 유지보수
  .github/workflows/commerce-payment-cd.yml
  .github/workflows/docker-integrate-ci.yml
  .github/workflows/eureka-gateway-cd.yml
  .github/workflows/integrate-ci.yml
  auth-service/settings.gradle
  auth-service/src/main/resources/application-prod.yml
  auth-service/src/main/resources/logback.xml
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/configuration/RedissonConfig.java
  commerce-service/src/main/resources/application-prod.yml
  commerce-service/src/main/resources/logback.xml
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/resources/application-dev.yml
  delivery-service/src/main/resources/application-prod.yml
  delivery-service/src/main/resources/logback.xml
  docker/docker-compose.commerce-payment.yml
  docker/docker-compose.db.yml
  docker/docker-compose.delivery-notification.yml
  docker/docker-compose.eureka-gateway.yml
  docker/docker-compose.kafka.yml
  docker/docker-compose.monitor.yml
  docker/docker-compose.redis.yml
  docker/docker-compose.service.yml
  docker/docker-compose.user-auth.yml
  eureka-server/src/main/resources/application-prod.yml
  gateway/src/main/resources/application-prod.yml
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-prod.yml
  notification-service/src/main/resources/logback.xml
  payment-service/src/main/resources/application-dev.yml
  payment-service/src/main/resources/application-prod.yml
  payment-service/src/main/resources/logback.xml
  user-service/src/main/resources/application-prod.yml
  user-service/src/main/resources/logback.xml
Labels: feat

#132 Fix/product pre order
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/ProductCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/ProductUpdateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/StockCreateRequestDto.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/dto/request/StockUpdateRequestDto.java
  commerce-service/src/test/java/com/pickple/commerceservice/application/service/OrderServiceTest.java
Labels: fix, refactor

#135 README 업데이트
  README.md
Labels: docs

#144 refactor: #141 유저 email feign 파라미터 이름 수정
  user-service/src/main/java/com/pickple/user/presentation/controller/UserController.java
Labels: refactor

#139 Feature/order
  commerce-service/build.gradle
  commerce-service/src/main/java/com/pickple/commerceservice/application/service/OrderService.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceErrorCode.java
  commerce-service/src/main/java/com/pickple/commerceservice/exception/CommerceExceptionHandler.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/DeliveryClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/PaymentClient.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/fallback/DeliveryClientFallback.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/feign/fallback/PaymentClientFallback.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/OrderMessagingProducerService.java
  commerce-service/src/main/java/com/pickple/commerceservice/infrastructure/messaging/events/NotificationCreateRequestEvent.java
  commerce-service/src/main/java/com/pickple/commerceservice/presentation/controller/OrderController.java
  commerce-service/src/main/resources/application-dev.yml
  commerce-service/src/main/resources/application-prod.yml
Labels: fix

#143 Fix: 알림에서 User feign 요청 시 권한 에러 해결 위해 X-User-Role 추가
  docker/db-init/notification/init-notification.sql
  notification-service/src/main/java/com/pickple/notification_service/application/dto/NotificationRespDto.java
  notification-service/src/main/java/com/pickple/notification_service/application/service/EmailService.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/feign/UserFeignClient.java
  notification-service/src/main/java/com/pickple/notification_service/infrastructure/messaging/events/EmailCreateRequestEvent.java
  notification-service/src/main/java/com/pickple/notification_service/presentation/NotificationController.java
  payment-service/src/main/java/com/pickple/payment_service/presentation/controller/PaymentController.java
Labels: fix

#145 refactor: NotificationCategoryEnum 수정
  notification-service/src/main/java/com/pickple/notification_service/domain/model/NotificationCategoryEnum.java
Labels: refactor

#140 fix: deliveryDetailList 이름 변경
  .github/workflows/build-ci.yml
  .github/workflows/docker-integrate-ci.yml
  README.md
  delivery-service/src/main/java/com/pickple/delivery/application/dto/response/DeliveryInfoResponseDto.java
  delivery-service/src/main/java/com/pickple/delivery/application/events/NotificationSendEvent.java
  delivery-service/src/main/java/com/pickple/delivery/application/mapper/DeliveryMapper.java
  delivery-service/src/main/java/com/pickple/delivery/application/service/DeliveryApplicationService.java
  delivery-service/src/main/java/com/pickple/delivery/infrastructure/feign/OrderFeignClient.java
  docker/dev.env
  docker/docker-compose.commerce-payment.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.service.yml
Labels: fix

#148 docs: #147 README 업데이트
  README.md
Labels: docs
